trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
